Importing modules

In [2]:
import torch
import numpy as np

Basics

In [ ]:
x = torch.tensor([1,2,3],dtype=torch.int32)
x

In [ ]:
y = torch.randn(2,3)
y

In [ ]:
z = torch.ones(2,3)
z

In [ ]:
z.add_(y)   # _ indicates that it is an in-place funciton 
z

In [ ]:
torch.cuda.is_available()

Gradient

In [78]:
x = torch.tensor([1,2,3,4],dtype=torch.float32,requires_grad=True)
y = torch.tensor([10,20,30,40],dtype=torch.float32,requires_grad=True)
# print(x.shape)
# y = x+2
z = (y-x).mean()
print(z)

z.backward()
print(x.grad)
print(y.grad)


tensor(22.5000, grad_fn=<MeanBackward0>)
tensor([-0.2500, -0.2500, -0.2500, -0.2500])
tensor([0.2500, 0.2500, 0.2500, 0.2500])


In [7]:
x = torch.ones(3, requires_grad=True)
y = 2*x
z = 3*y.sum()
z.backward()
y.grad

C:\Users\Home\AppData\Local\Temp\ipykernel_13192\1992633495.py:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:485.)
  y.grad


Sample model working

In [69]:
weight = torch.randn(5, requires_grad=True)
print('Weight: ',weight)

def model(input):
    output = 3*input    
    return output

for epoch in range(10):
    model_output = model(weight)
    model_output.backward(torch.ones_like(model_output))    
    print(weight.grad)
    # weight.grad.zero_() # if you want to empty the gradient
    

Weight:  tensor([-0.3754,  0.4703, -0.6407,  2.1995, -0.3588], requires_grad=True)
tensor([3., 3., 3., 3., 3.])
tensor([6., 6., 6., 6., 6.])
tensor([9., 9., 9., 9., 9.])
tensor([12., 12., 12., 12., 12.])
tensor([15., 15., 15., 15., 15.])
tensor([18., 18., 18., 18., 18.])
tensor([21., 21., 21., 21., 21.])
tensor([24., 24., 24., 24., 24.])
tensor([27., 27., 27., 27., 27.])
tensor([30., 30., 30., 30., 30.])


In [67]:
print(torch.tensor([5,4,5]).size())

torch.Size([3])
