Importing modules

In [1]:
import torch
import numpy as np

Basics

In [2]:
x = torch.tensor([1,2,3],dtype=torch.int32)
x

tensor([1, 2, 3], dtype=torch.int32)

In [3]:
y = torch.randn(2,3)
y

tensor([[-0.2624,  0.7929,  2.4588],
        [-0.3986, -0.0117,  0.0379]])

In [4]:
z = torch.ones(2,3)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
z.add_(y)   # _ indicates that it is an in-place funciton 
z

tensor([[0.7376, 1.7929, 3.4588],
        [0.6014, 0.9883, 1.0379]])

In [6]:
torch.cuda.is_available()

False

Gradient

In [7]:
x = torch.tensor([1,2,3,4],dtype=torch.float32,requires_grad=True)
y = torch.tensor([10,20,30,40],dtype=torch.float32,requires_grad=True)
# print(x.shape)
# y = x+2
z = (y-x).mean()
print(z)

z.backward()
print(x.grad)
print(y.grad)


tensor(22.5000, grad_fn=<MeanBackward0>)
tensor([-0.2500, -0.2500, -0.2500, -0.2500])
tensor([0.2500, 0.2500, 0.2500, 0.2500])


In [8]:
x = torch.ones(3, requires_grad=True)
y = torch.tensor(2*x,requires_grad=True)
z = 3*y
z.backward(torch.ones_like(z))
y.grad

C:\Users\Home\AppData\Local\Temp\ipykernel_10132\820112559.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(2*x,requires_grad=True)


tensor([3., 3., 3.])

Sample model working

In [9]:
weight = torch.randn(5, requires_grad=True)
print('Weight: ',weight)

def model(input):
    output = 3*input    
    return output

for epoch in range(10):
    model_output = model(weight)
    model_output.backward(torch.ones_like(model_output))    
    print(weight.grad)
    # weight.grad.zero_() # if you want to empty the gradient

Weight:  tensor([-0.1647, -1.8984,  1.3119, -0.0416, -1.2620], requires_grad=True)
tensor([3., 3., 3., 3., 3.])
tensor([6., 6., 6., 6., 6.])
tensor([9., 9., 9., 9., 9.])
tensor([12., 12., 12., 12., 12.])
tensor([15., 15., 15., 15., 15.])
tensor([18., 18., 18., 18., 18.])
tensor([21., 21., 21., 21., 21.])
tensor([24., 24., 24., 24., 24.])
tensor([27., 27., 27., 27., 27.])
tensor([30., 30., 30., 30., 30.])


Forward and Backward propogation

In [22]:
x = torch.tensor(1.)
w = torch.tensor(1.,requires_grad=True)
y = torch.tensor(2.)
def model(x,w):
    return x*w

# forward pass 
y_hat = model(x,w)
L = (y_hat - y)**2
print(L)  

# backward pass
L.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
