Importing modules

In [74]:
import torch
import numpy as np

Basics

In [75]:
x = torch.tensor([1,2,3],dtype=torch.int32)
x

tensor([1, 2, 3], dtype=torch.int32)

In [76]:
y = torch.randn(2,3)
y

tensor([[ 0.2247,  0.3890,  0.5693],
        [-1.1246, -0.6573, -2.1084]])

In [77]:
z = torch.ones(2,3)
z

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [78]:
z.add_(y)   # _ indicates that it is an in-place funciton 
z

tensor([[ 1.2247,  1.3890,  1.5693],
        [-0.1246,  0.3427, -1.1084]])

In [79]:
torch.cuda.is_available()

False

Gradient

In [80]:
x = torch.tensor([1,2,3,4],dtype=torch.float32,requires_grad=True)
y = torch.tensor([10,20,30,40],dtype=torch.float32,requires_grad=True)
# print(x.shape)
# y = x+2
z = (y-x).mean()
print(z)

z.backward()
print(x.grad)
print(y.grad)


tensor(22.5000, grad_fn=<MeanBackward0>)
tensor([-0.2500, -0.2500, -0.2500, -0.2500])
tensor([0.2500, 0.2500, 0.2500, 0.2500])


In [81]:
x = torch.ones(3, requires_grad=True)
y = torch.tensor(2*x,requires_grad=True)
z = 3*y
z.backward(torch.ones_like(z))
y.grad

C:\Users\Home\AppData\Local\Temp\ipykernel_13192\820112559.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(2*x,requires_grad=True)


tensor([3., 3., 3.])

Sample model working

In [82]:
weight = torch.randn(5, requires_grad=True)
print('Weight: ',weight)

def model(input):
    output = 3*input    
    return output

for epoch in range(10):
    model_output = model(weight)
    model_output.backward(torch.ones_like(model_output))    
    print(weight.grad)
    # weight.grad.zero_() # if you want to empty the gradient

Weight:  tensor([ 0.4889,  0.1669, -0.3187, -1.0139,  0.2332], requires_grad=True)
tensor([3., 3., 3., 3., 3.])
tensor([6., 6., 6., 6., 6.])
tensor([9., 9., 9., 9., 9.])
tensor([12., 12., 12., 12., 12.])
tensor([15., 15., 15., 15., 15.])
tensor([18., 18., 18., 18., 18.])
tensor([21., 21., 21., 21., 21.])
tensor([24., 24., 24., 24., 24.])
tensor([27., 27., 27., 27., 27.])
tensor([30., 30., 30., 30., 30.])


Forward and Backward propogation

In [83]:
x = torch.randn(3,requires_grad=True)
w = torch.randn(3,requires_grad=True)
y = torch.tensor(2)
def model(x,w):
    return x*w

y_hat = model(x,w)
s = y_hat.clone().detach().requires_grad - y
L = s.clone().detach().requires_grad=True**2
x.grad

RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.