Importing

In [45]:
import pandas as pd

Loading data

In [46]:
df = pd.read_csv('wine.csv')

Setting limit to display

In [47]:
pd.options.display.max_rows = 5
pd.options.display.max_columns = 30

Various beginner things

In [48]:
df

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
..    ...      ...         ...   ...   ...  ...      ...         ...   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065  
1                    0.26     1.28       4.38  1.05  3.40     1050  
..                    ...      ...        ...   ...   ...      ...  
176                  0.53     1.46       9.30  0.60  1.62      840  
177                  0.56     1.35       9.20  0.61  1.60      560  

[178 rows x 14 columns]

In [49]:
df.head(3)

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185

In [50]:
df.columns

Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline'],
      dtype='object')

In [51]:
df['Ash'][1]   # Column X Row format indexing

2.14

In [52]:
df.loc[1][["Hue","Wine"]]   # Column X Row format indexing

Hue     1.05
Wine    1.00
Name: 1, dtype: float64

In [53]:
df.iloc[1][3]    # Row X Column format indexing

2.14

In [54]:
df.iloc[3:12]

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
3      1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4      1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..   ...      ...         ...   ...   ...  ...      ...         ...   
10     1    14.10        2.16  2.30  18.0  105     2.95        3.32   
11     1    14.12        1.48  2.32  16.8   95     2.20        2.43   

    Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
3                   0.24     2.18       7.80  0.86  3.45     1480  
4                   0.39     1.82       4.32  1.04  2.93      735  
..                   ...      ...        ...   ...   ...      ...  
10                  0.22     2.38       5.75  1.25  3.17     1510  
11                  0.26     1.57       5.00  1.17  2.82     1280  

[9 rows x 14 columns]

Sorting

In [55]:
df2 = df.sort_values(['Alcohol','Mg'], ascending=[1,0])  # Sort Alcohol in ascending, Mg desc
df2
df2.iloc[1,2]

0.74

Add column

In [56]:
df['HUE OD'] = df['Hue'] + df['OD']
df

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
..    ...      ...         ...   ...   ...  ...      ...         ...   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  HUE OD  
0                    0.28     2.29       5.64  1.04  3.92     1065    4.96  
1                    0.26     1.28       4.38  1.05  3.40     1050    4.45  
..                    ...      ...        ...   ...   ...      ...     ...  
176                  0.53     1.46       9.30  0.60  1.62      840    2.22  
177                  0.56     1.35       9.20  0.61  1.60      560    2.21  

[178 rows x 15 columns]

Drop column

In [57]:
df = df.drop(columns=['Nonflavanoid.phenols'])
df

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  Proanth  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06     2.29   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76     1.28   
..    ...      ...         ...   ...   ...  ...      ...         ...      ...   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68     1.46   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76     1.35   

     Color.int   Hue    OD  Proline  HUE OD  
0         5.64  1.04  3.92     1065    4.96  
1         4.38  1.05  3.40     1050    4.45  
..         ...   ...   ...      ...     ...  
176       9.30  0.60  1.62      840    2.22  
177       9.20  0.61  1.60      560    2.21  

[178 rows x 14 columns]

In [58]:
col = list(df.columns)
col
df = df[col[0:4]+col[9:11]+[col[-1]]]
df

Wine  Alcohol  Malic.acid   Ash  Color.int   Hue  HUE OD
0       1    14.23        1.71  2.43       5.64  1.04    4.96
1       1    13.20        1.78  2.14       4.38  1.05    4.45
..    ...      ...         ...   ...        ...   ...     ...
176     3    13.17        2.59  2.37       9.30  0.60    2.22
177     3    14.13        4.10  2.74       9.20  0.61    2.21

[178 rows x 7 columns]

Saving to desired format

In [59]:
df.to_csv('modified.csv', index ='False')

In [60]:
df_saved = pd.read_csv('modified.csv')
df_saved

Unnamed: 0  Wine  Alcohol  Malic.acid   Ash  Color.int   Hue  HUE OD
0             0     1    14.23        1.71  2.43       5.64  1.04    4.96
1             1     1    13.20        1.78  2.14       4.38  1.05    4.45
..          ...   ...      ...         ...   ...        ...   ...     ...
176         176     3    13.17        2.59  2.37       9.30  0.60    2.22
177         177     3    14.13        4.10  2.74       9.20  0.61    2.21

[178 rows x 8 columns]

Filtering data

In [61]:
df.tail()

Wine  Alcohol  Malic.acid   Ash  Color.int   Hue  HUE OD
173     3    13.71        5.65  2.45        7.7  0.64    2.38
174     3    13.40        3.91  2.48        7.3  0.70    2.26
175     3    13.27        4.28  2.26       10.2  0.59    2.15
176     3    13.17        2.59  2.37        9.3  0.60    2.22
177     3    14.13        4.10  2.74        9.2  0.61    2.21

In [62]:
df.loc[(df['Alcohol'] > 14) & (df['Ash']<2.50)]

Wine  Alcohol  Malic.acid   Ash  Color.int   Hue  HUE OD
0       1    14.23        1.71  2.43       5.64  1.04    4.96
5       1    14.20        1.76  2.45       6.75  1.05    3.90
..    ...      ...         ...   ...        ...   ...     ...
56      1    14.22        1.70  2.30       6.38  0.94    4.25
172     3    14.16        2.51  2.48       9.70  0.62    2.33

[16 rows x 7 columns]

Large data

In [78]:
new_df = pd.DataFrame(columns=df.columns)

for df in pd.read_csv('modified.csv', chunksize=10):
    results = df.groupby(['Ash']).count()
    new_df = pd.concat([new_df, results])
    
new_df

Unnamed: 0 Wine Alcohol Malic.acid  Ash Color.int Hue HUE OD
2.14          1    1       1          1  NaN         1   1      1
2.17          1    1       1          1  NaN         1   1      1
...         ...  ...     ...        ...  ...       ...  ..    ...
2.48          2    2       2          2  NaN         2   2      2
2.74          1    1       1          1  NaN         1   1      1

[166 rows x 8 columns]

In [6]:
import numpy as np
a = np.zeros(4)
print(a.shape)
print(a)
a = np.zeros((4,))
print(a.shape)
print(a)

(4,)
[0. 0. 0. 0.]
(4,)
[0. 0. 0. 0.]


In [8]:
import numpy as np
a = np.zeros(4)
print(a.shape)
print(a)
a = np.zeros((4,5))
print(a.shape)
print(a)

(4,)
[0. 0. 0. 0.]
(4, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
